### ISSUE TITLE
Artifacts on lidar clouds and depthmaps

### ISSUE THREAD

**Issue by Kasatusss** [mileyan/Pseudo_Lidar_V2#8]
Hello! Thanks for your work.

I have some strange effect using your methods: I've got depth maps - and they are ok. But using the `./src/preprocess/generate_lidar_from_depth.py` script to get lidar clouds from depth maps I get artifacts near the coordinate center, while other areas look quite good. 
Here is an example:
![pc_000](https://user-images.githubusercontent.com/57013915/85918472-b40d3f80-b86b-11ea-8606-2c12c62c16be.png)
![pc_001](https://user-images.githubusercontent.com/57013915/85918474-b4a5d600-b86b-11ea-8829-6f772d320cd7.png)

This problem appears both before GDC and after.

Can anyone help me to deal with these artifacts?

**Comment by Kasatusss** [comment]
There was a mistake in my previous message.

Depth maps are not ok and such artifacts appears primarily on them. Here is an example of depthmap before GDC:
![DM](https://user-images.githubusercontent.com/57013915/86216518-d6160300-bb86-11ea-90c2-a3d361da32a1.png)

On the circled area some points have value =-1, and it corresponds to infinitely distant points. But some of the points have small value >0 and small depth. The second ones leads to such artifacts that were mentiond in the previous message. So `./src/preprocess/generate_lidar_from_depth.py` works well. 

The question is how to overcome these artifacts that arise at the stage of using the neural network?

**Comment by tomsal** [comment]
Hi @Kasatusss!

I am experiencing similar artifacts close to the coordinate center. In each depth map I have generated the minimal value was always >= 1. Thus, I do not think this is the issue. Did you look into this any further?

**Comment by YurongYou** [comment]
Hi all,

Thanks for your interest! Yes we observed such issues too, and we think this should be due to lacking enough supervision when training depth estimation models on upper part of image (most images only have LiDAR signals on the lower part). But this should not affect the detection too much since in the evaluation we can cut off those area.

**Comment by tomsal** [comment]
Hi @YurongYou 

Thanks for clarifying! I think that makes sense, especially since I have the feeling that these issues often correlate with parts of the images that show sky.

**Comment by mohamedgamal7** [comment]
generated point clouds

![Screenshot 2021-05-17 095714](https://user-images.githubusercontent.com/67305499/118571151-b3c8ac00-b77d-11eb-8822-eccd8033b441.jpg)

provided point clouds

![s](https://user-images.githubusercontent.com/67305499/118571173-b7f4c980-b77d-11eb-91e7-ae3f703ef6ed.jpg)

Hi  @YurongYou @noble-born I am trying to generate point clouds from depth using the script  provided but the point clouds are not correctly matched with the bounding boxes like those of the point clouds you provided.

Is this because you use GDC or something else ?
also I noticed that the bin files for the same image are different, my generated file is about 4.7mb while the one you provided is 5.6 mb.

edit: I even tried the training disparities given in the pseudo lidar repo but the results where close to the generated points clouds
I also tried the gdc but nothing has changed
